// This file is generated by Firebase Studio.
'use server';
/**
 * @fileOverview Generates flashcards from a given topic.
 *
 * - generateFlashcards - A function that handles the flashcard generation process.
 * - GenerateFlashcardsInput - The input type for the generateFlashcards function.
 * - GenerateFlashcardsOutput - The return type for the generateFlashcards function.
 */

import {ai} from '@/ai/ai-instance';
import {z} from 'genkit';

const GenerateFlashcardsInputSchema = z.object({
  topic: z.string().describe('The topic for which to generate flashcards.'),
});
export type GenerateFlashcardsInput = z.infer<typeof GenerateFlashcardsInputSchema>;

const GenerateFlashcardsOutputSchema = z.object({
  flashcards: z.array(
    z.object({
      front: z.string().describe('The content of the front of the flashcard.'),
      back: z.string().describe('The content of the back of the flashcard.'),
    })
  ).describe('An array of flashcards generated for the given topic.'),
});
export type GenerateFlashcardsOutput = z.infer<typeof GenerateFlashcardsOutputSchema>;

export async function generateFlashcards(input: GenerateFlashcardsInput): Promise<GenerateFlashcardsOutput> {
  return generateFlashcardsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateFlashcardsPrompt',
  input: {
    schema: z.object({
      topic: z.string().describe('The topic for which to generate flashcards.'),
    }),
  },
  output: {
    schema: z.object({
      flashcards: z.array(
        z.object({
          front: z.string().describe('The content of the front of the flashcard.'),
          back: z.string().describe('The content of the back of the flashcard.'),
        })
      ).describe('An array of flashcards generated for the given topic.'),
    }),
  },
  prompt: `You are an expert in creating flashcards for learning new subjects.

  Given the topic: {{{topic}}}, generate a set of flashcards that will help the user learn the topic effectively.
  Each flashcard should have a clear and concise front and back.
  Generate at least 5 flashcards.

  Output the flashcards as a JSON array of objects, where each object has a 'front' and 'back' field.
  `,
});

const generateFlashcardsFlow = ai.defineFlow<
  typeof GenerateFlashcardsInputSchema,
  typeof GenerateFlashcardsOutputSchema
>({
  name: 'generateFlashcardsFlow',
  inputSchema: GenerateFlashcardsInputSchema,
  outputSchema: GenerateFlashcardsOutputSchema,
}, async input => {
  const {output} = await prompt(input);
  return output!;
});
